"""als fas s

Revision ID: 66781120f004
Revises: 
Create Date: 2024-12-04 13:31:03.059510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66781120f004'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_data', sa.Text(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('logo', sa.String(length=120), nullable=True),
    sa.Column('bg_color', sa.String(length=7), nullable=True),
    sa.Column('bg_font_color', sa.String(length=7), nullable=True),
    sa.Column('title_color', sa.String(length=7), nullable=True),
    sa.Column('title_font_color', sa.String(length=7), nullable=True),
    sa.Column('attribut_color', sa.String(length=7), nullable=True),
    sa.Column('attribut_font_color', sa.String(length=7), nullable=True),
    sa.Column('fontFamily', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('consumed_reports', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ip_ad', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('post_code', sa.String(length=500), nullable=True),
    sa.Column('free_rep', sa.Boolean(), nullable=True),
    sa.Column('verif_code', sa.String(length=500), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.Column('subscription_ends', sa.DateTime(), nullable=True),
    sa.Column('reports_count', sa.Integer(), nullable=True),
    sa.Column('code_timer', sa.DateTime(), nullable=True),
    sa.Column('token_reset_pass', sa.Text(), nullable=True),
    sa.Column('subs_type', sa.String(length=500), nullable=True),
    sa.Column('subs_start', sa.DateTime(), nullable=True),
    sa.Column('downloaded_current', sa.Integer(), nullable=True),
    sa.Column('downloaded_history', sa.Integer(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('logo'),
    sa.UniqueConstraint('website')
    )
    op.create_table('Reports_Logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=500), nullable=True),
    sa.Column('property_type', sa.String(length=500), nullable=True),
    sa.Column('download_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=122), nullable=True),
    sa.Column('card_id', sa.String(length=122), nullable=True),
    sa.Column('ccv', sa.Integer(), nullable=True),
    sa.Column('exp_month', sa.String(length=122), nullable=True),
    sa.Column('exp_year', sa.String(length=122), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('name_on_card', sa.String(length=122), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userprofile')
    op.drop_table('subscription')
    op.drop_table('payment_methods')
    op.drop_table('Reports_Logs')
    op.drop_table('users')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
